before_script:
  - cd visual-monitor
  # Instead of npm install, we save time by getting
  # by using a gzipped file.
  - tar zxf node_modules.tar.gz

script:
  - PROVIDER_PREFIX=browserstack SELECTED_CAPS=chrome mocha
