before_script:
  # Instead of npm install, we save time by using a gzipped file.
  - cd visual-monitor
  - tar zxf node_modules.tar.gz

script:
  - PROVIDER_PREFIX=browserstack SELECTED_CAPS=chrome mocha
