before_script:
  # Instead of npm install, we save time by using a gzipped file.
  - cd visual-monitor
  - npm install

script:
  - PROVIDER_PREFIX=browserstack SELECTED_CAPS=ie11 mocha
  - PROVIDER_PREFIX=browserstack SELECTED_CAPS=chrome mocha
