before_script:
  - set -e
  # Instead of npm install, we save time by using a gzipped file.
  - cd ./visual-monitor
  - npm install
  - cd ..

  - cd ./behat
  - cp behat.local.yml.example behat.local.yml
  - composer install
  - cd ..

script:
  - cd ./visual-monitor
  - PROVIDER_PREFIX=browserstack SELECTED_CAPS=ie11 mocha
  - PROVIDER_PREFIX=browserstack SELECTED_CAPS=chrome mocha
  - cd ..

  - cd ./behat
  - ./bin/behat
